import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Course Catalog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased mobile:max-w-fit mobile:m-4 lmobile:max-w-fit lmobile:mx-auto tablet:max-w-[65%] desktop:max-w-[65%] ldesktop:max-w-[65%] laptop:max-w-[65%] mx-auto`}
      >
        {children}
      </body>
    </html>
  );
}
